// Generated by CoffeeScript 1.7.1
(function() {
  var $, a, defaultControls, getWebGL, hasWebGL, init, s, u, _fn, _i, _len;

  $ = function(_) {
    return document.getElementById(_);
  };

  // ═══════════════════════════════════════════════════════════
  //  Apply saved garage colors to the in-game ship
  // ═══════════════════════════════════════════════════════════
  function applyGarageColorsToGame(hexGL) {
    try {
      var raw = window.localStorage.getItem('hexgl.garageCustomization');
      if (!raw) {
        console.log('launch.js: No garage customization found');
        return;
      }
      var gc = JSON.parse(raw);
      console.log('launch.js: Applying garage customization', gc);

      // Get the track object (contains materials)
      var track = hexGL.track;
      if (!track || !track.materials || !track.materials.ship) {
        console.warn('launch.js: Track/materials not available');
        return;
      }

      // Apply ship body color tint
      if (typeof gc.shipColor === 'number' && gc.shipColor !== 0xffffff) {
        var shipMat = track.materials.ship;

        // ShaderMaterial (high quality) — uDiffuseColor uniform
        if (shipMat.uniforms && shipMat.uniforms['uDiffuseColor']) {
          shipMat.uniforms['uDiffuseColor'].value.setHex(gc.shipColor);
          console.log('launch.js: Applied ship color (ShaderMaterial) 0x' + gc.shipColor.toString(16));
        }
        // MeshBasicMaterial / MeshPhongMaterial — .color property
        else if (shipMat.color && typeof shipMat.color.setHex === 'function') {
          shipMat.color.setHex(gc.shipColor);
          console.log('launch.js: Applied ship color (BasicMaterial) 0x' + gc.shipColor.toString(16));
        }
      }

      // Apply booster light color
      if (typeof gc.boosterColor === 'number') {
        // Try to find PointLights via the ship mesh children
        var shipControls = hexGL.components.shipControls;
        var shipMesh = shipControls && shipControls.mesh;
        if (shipMesh) {
          // The booster is a child of the ship mesh
          shipMesh.children.forEach(function(child) {
            if (child.children) {
              child.children.forEach(function(grandchild) {
                if (grandchild instanceof THREE.PointLight) {
                  grandchild.color.setHex(gc.boosterColor);
                  console.log('launch.js: Applied booster color 0x' + gc.boosterColor.toString(16));
                }
              });
            }
          });
          // Also check direct children
          shipMesh.children.forEach(function(child) {
            if (child instanceof THREE.PointLight) {
              child.color.setHex(gc.boosterColor);
              console.log('launch.js: Applied booster color (direct) 0x' + gc.boosterColor.toString(16));
            }
          });
        }
      }
    } catch(e) {
      console.warn('launch.js: Error applying garage customization', e);
    }
  }

  init = function(controlType, quality, hud, godmode) {
    var hexGL, progressbar;
    hexGL = new bkcore.hexgl.HexGL({
      document: document,
      width: window.innerWidth,
      height: window.innerHeight,
      container: $('main'),
      overlay: $('overlay'),
      gameover: $('step-5'),
      quality: quality,
      difficulty: 0,
      hud: hud === 1,
      controlType: controlType,
      godmode: godmode,
      track: 'Cityscape'
    });
    window.hexGL = hexGL;
    progressbar = $('progressbar');
    return hexGL.load({
      onLoad: function() {
        console.log('LOADED.');
        hexGL.init();

        // ── Apply garage customization to the in-game ship ──
        applyGarageColorsToGame(hexGL);

        $('step-3').style.display = 'none';
        $('step-4').style.display = 'block';
        return hexGL.start();
      },
      onError: function(s) {
        return console.error("Error loading " + s + ".");
      },
      onProgress: function(p, t, n) {
        console.log("LOADED " + t + " : " + n + " ( " + p.loaded + " / " + p.total + " ).");
        return progressbar.style.width = "" + (p.loaded / p.total * 100) + "%";
      }
    });
  };

  u = bkcore.Utils.getURLParameter;

  defaultControls = bkcore.Utils.isTouchDevice() ? 1 : 0;

  s = [['controlType', ['KEYBOARD', 'TOUCH', 'LEAP MOTION CONTROLLER', 'GAMEPAD'], defaultControls, defaultControls, 'Controls: '], ['quality', ['LOW', 'MID', 'HIGH', 'VERY HIGH'], 3, 3, 'Quality: '], ['hud', ['OFF', 'ON'], 1, 1, 'HUD: '], ['godmode', ['OFF', 'ON'], 0, 1, 'Godmode: ']];

  _fn = function(a) {
    var e, f, _ref;
    a[3] = (_ref = u(a[0])) != null ? _ref : a[2];
    e = $("s-" + a[0]);
    (f = function() {
      return e.innerHTML = a[4] + a[1][a[3]];
    })();
    return e.onclick = function() {
      return f(a[3] = (a[3] + 1) % a[1].length);
    };
  };
  for (_i = 0, _len = s.length; _i < _len; _i++) {
    a = s[_i];
    _fn(a);
  }

  $('step-2').onclick = function() {
    $('step-2').style.display = 'none';
    $('step-3').style.display = 'block';
    return init(s[0][3], s[1][3], s[2][3], s[3][3]);
  };

  $('step-5').onclick = function() {
    return window.location.reload();
  };

  $('s-credits').onclick = function() {
    $('step-1').style.display = 'none';
    return $('credits').style.display = 'block';
  };

  $('credits').onclick = function() {
    $('step-1').style.display = 'block';
    return $('credits').style.display = 'none';
  };

  // ═══════════════════════════════════════════════════════════
  //  GARAGE — Navigation & Panel Logic
  // ═══════════════════════════════════════════════════════════

  var garagePanelOpen = false;

  function returnToMenu() {
    // Close panel if open
    closePanelIfOpen();
    $('garage').style.display = 'none';
    $('step-1').style.display = 'block';
    GarageRenderer.destroy();
  }

  function preventGarageClickBubble(event) {
    if (!event) return;
    event.stopPropagation();
    if (event.stopImmediatePropagation) {
      event.stopImmediatePropagation();
    }
  }

  // ── Toast Notification ──
  function showToast(message) {
    var toast = $('garage-toast');
    if (!toast) return;
    toast.textContent = message;
    toast.classList.add('show');
    setTimeout(function() {
      toast.classList.remove('show');
    }, 2200);
  }

  // ── Save ──
  function saveGarageState() {
    var success = GarageRenderer.saveCustomization();
    if (success) {
      showToast('✓ Personalización guardada');
    } else {
      showToast('✗ Error al guardar');
    }
  }

  // ── Panel toggle ──
  function togglePanel() {
    garagePanelOpen = !garagePanelOpen;
    var panel = $('garage-panel');
    var viewport = $('garage-viewport');
    var toggleBtn = $('garage-toggle-panel');

    if (garagePanelOpen) {
      panel.classList.add('open');
      viewport.classList.add('panel-open');
      toggleBtn.classList.add('panel-active');
      // Sync swatches with current customization
      syncSwatchesWithState();
    } else {
      panel.classList.remove('open');
      viewport.classList.remove('panel-open');
      toggleBtn.classList.remove('panel-active');
    }

    // Trigger resize so the 3D viewport adjusts its aspect ratio
    setTimeout(function() {
      GarageRenderer.onWindowResize();
    }, 400);
  }

  function closePanelIfOpen() {
    if (garagePanelOpen) {
      garagePanelOpen = false;
      var panel = $('garage-panel');
      var viewport = $('garage-viewport');
      var toggleBtn = $('garage-toggle-panel');
      if (panel) panel.classList.remove('open');
      if (viewport) viewport.classList.remove('panel-open');
      if (toggleBtn) toggleBtn.classList.remove('panel-active');
    }
  }

  // ── Sync swatch active state with current customization ──
  function syncSwatchesWithState() {
    var state = GarageRenderer.getCustomization();

    // Ship color swatches
    var shipSwatches = document.querySelectorAll('#ship-color-grid .color-swatch');
    for (var i = 0; i < shipSwatches.length; i++) {
      var colorVal = parseInt(shipSwatches[i].getAttribute('data-color'));
      if (colorVal === state.shipColor) {
        shipSwatches[i].classList.add('active');
      } else {
        shipSwatches[i].classList.remove('active');
      }
    }
    // Update custom picker
    var shipPicker = $('ship-custom-color');
    if (shipPicker) shipPicker.value = '#' + ('000000' + state.shipColor.toString(16)).slice(-6);

    // Booster color swatches
    var boosterSwatches = document.querySelectorAll('#booster-color-grid .color-swatch');
    for (var j = 0; j < boosterSwatches.length; j++) {
      var bColorVal = parseInt(boosterSwatches[j].getAttribute('data-color'));
      if (bColorVal === state.boosterColor) {
        boosterSwatches[j].classList.add('active');
      } else {
        boosterSwatches[j].classList.remove('active');
      }
    }
    // Update custom picker
    var boosterPicker = $('booster-custom-color');
    if (boosterPicker) boosterPicker.value = '#' + ('000000' + state.boosterColor.toString(16)).slice(-6);
  }

  // ── Open Garage ──
  $('s-garage').onclick = function() {
    $('step-1').style.display = 'none';
    $('garage').style.display = 'block';
    GarageRenderer.init($('garage-viewport'));
  };

  // ── Setup event listeners ──
  function setupGarageListeners() {
    // Prevent clicks from bubbling through the garage
    $('garage').addEventListener('click', preventGarageClickBubble);
    var viewportEl = $('garage-viewport');
    if (viewportEl) {
      viewportEl.addEventListener('click', preventGarageClickBubble);
    }

    // ── Panel toggle ──
    $('garage-toggle-panel').onclick = function(event) {
      preventGarageClickBubble(event);
      togglePanel();
      return false;
    };

    // ── Ship color swatches ──
    var shipGrid = $('ship-color-grid');
    if (shipGrid) {
      shipGrid.addEventListener('click', function(event) {
        var swatch = event.target.closest('.color-swatch');
        if (!swatch) return;
        preventGarageClickBubble(event);

        var colorHex = parseInt(swatch.getAttribute('data-color'));
        GarageRenderer.setShipColor(colorHex);

        // Update active state
        var siblings = shipGrid.querySelectorAll('.color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
        swatch.classList.add('active');

        // Update custom picker to match
        var picker = $('ship-custom-color');
        if (picker) picker.value = '#' + ('000000' + colorHex.toString(16)).slice(-6);
      });
    }

    // ── Ship custom color picker ──
    var shipPicker = $('ship-custom-color');
    if (shipPicker) {
      shipPicker.addEventListener('input', function() {
        var hexVal = parseInt(this.value.replace('#', ''), 16);
        GarageRenderer.setShipColor(hexVal);

        // Deactivate all preset swatches
        var siblings = shipGrid.querySelectorAll('.color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
      });
    }

    // ── Booster color swatches ──
    var boosterGrid = $('booster-color-grid');
    if (boosterGrid) {
      boosterGrid.addEventListener('click', function(event) {
        var swatch = event.target.closest('.color-swatch');
        if (!swatch) return;
        preventGarageClickBubble(event);

        var colorHex = parseInt(swatch.getAttribute('data-color'));
        GarageRenderer.setBoosterColor(colorHex);

        // Update active state
        var siblings = boosterGrid.querySelectorAll('.color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
        swatch.classList.add('active');

        // Update custom picker to match
        var picker = $('booster-custom-color');
        if (picker) picker.value = '#' + ('000000' + colorHex.toString(16)).slice(-6);
      });
    }

    // ── Booster custom color picker ──
    var boosterPicker = $('booster-custom-color');
    if (boosterPicker) {
      boosterPicker.addEventListener('input', function() {
        var hexVal = parseInt(this.value.replace('#', ''), 16);
        GarageRenderer.setBoosterColor(hexVal);

        // Deactivate all preset swatches
        var siblings = boosterGrid.querySelectorAll('.color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
      });
    }

    // ── Reset button ──
    var resetBtn = $('garage-reset-colors');
    if (resetBtn) {
      resetBtn.onclick = function(event) {
        preventGarageClickBubble(event);
        GarageRenderer.setShipColor(0xffffff);
        GarageRenderer.setBoosterColor(0x00a2ff);
        syncSwatchesWithState();
        showToast('↺ Colores restablecidos');
        return false;
      };
    }
  }

  setupGarageListeners();

  // ── Save button ──
  $('garage-save').onclick = function(event) {
    preventGarageClickBubble(event);
    saveGarageState();
    return false;
  };

  // ── Back button ──
  $('garage-back').onclick = function(event) {
    preventGarageClickBubble(event);
    returnToMenu();
    return false;
  };

  hasWebGL = function() {
    var canvas, gl;
    gl = null;
    canvas = document.createElement('canvas');
    try {
      gl = canvas.getContext("webgl");
    } catch (_error) {}
    if (gl == null) {
      try {
        gl = canvas.getContext("experimental-webgl");
      } catch (_error) {}
    }
    return gl != null;
  };

  if (!hasWebGL()) {
    getWebGL = $('start');
    getWebGL.innerHTML = 'WebGL is not supported!';
    getWebGL.onclick = function() {
      return window.location.href = 'http://get.webgl.org/';
    };
  } else {
    $('start').onclick = function() {
      $('step-1').style.display = 'none';
      $('step-2').style.display = 'block';
      return $('step-2').style.backgroundImage = "url(css/help-" + s[0][3] + ".png)";
    };
  }

}).call(this);
