// Generated by CoffeeScript 1.7.1
(function() {
  var $, a, defaultControls, getWebGL, hasWebGL, init, s, u, _fn, _i, _len;

  $ = function(_) {
    return document.getElementById(_);
  };

  // ═══════════════════════════════════════════════════════════
  //  Apply saved garage colors to the in-game ship
  // ═══════════════════════════════════════════════════════════
  function garageHexStringToNumber(hexColor) {
    return parseInt(hexColor.replace('#', ''), 16);
  }

  function garageColorNumberToHexString(hexColor) {
    return '#' + ('000000' + hexColor.toString(16)).slice(-6).toLowerCase();
  }

  function getGaragePrefs() {
    if (bkcore && bkcore.garage && bkcore.garage.GaragePreferences) {
      return bkcore.garage.GaragePreferences.load();
    }
    console.warn('launch.js: GaragePreferences module is not available');
    return null;
  }

  function applyEngineColorToNode(node, engineColor, rootNode) {
    if (!node) return;

    if (node instanceof THREE.PointLight) {
      node.color.setHex(engineColor);
      console.log('launch.js: Applied booster light color 0x' + engineColor.toString(16));
    }

    if (node.material && node.material.color && typeof node.material.color.setHex === 'function') {
      if (node !== rootNode) {
        node.material.color.setHex(engineColor);
      }
    }

    if (node.color && typeof node.color.setHex === 'function') {
      node.color.setHex(engineColor);
    }

    if (node.children) {
      for (var i = 0; i < node.children.length; i++) {
        applyEngineColorToNode(node.children[i], engineColor, rootNode);
      }
    }
  }

  function applyGarageColorsToGame(hexGL) {
    try {
      var prefs = getGaragePrefs();
      if (!prefs) {
        return;
      }
      var bodyColor = garageHexStringToNumber(prefs.ship.colors.body);
      var engineColor = garageHexStringToNumber(prefs.ship.colors.engine);
      var trailHex = (prefs.ship.colors && prefs.ship.colors.trail)
        ? prefs.ship.colors.trail
        : ((prefs.ship.trail && prefs.ship.trail.color) ? prefs.ship.trail.color : '#ffffff');
      var trailColor = garageHexStringToNumber(trailHex);
      var trailSize = (prefs.ship.particles && typeof prefs.ship.particles.size === 'number')
        ? prefs.ship.particles.size
        : ((prefs.ship.trail && typeof prefs.ship.trail.size === 'number') ? prefs.ship.trail.size : 2);
      var materialPreset = (prefs.ship.material && prefs.ship.material.preset)
        ? prefs.ship.material.preset
        : 'metallic';
      console.log('launch.js: Applying garage customization', prefs);

      // Get the track object (contains materials)
      var track = hexGL.track;
      if (!track || !track.materials || !track.materials.ship) {
        console.warn('launch.js: Track/materials not available');
        return;
      }

      // Apply ship body color tint
      var shipMat = track.materials.ship;

      // ShaderMaterial (high quality) — uDiffuseColor uniform
      if (shipMat.uniforms && shipMat.uniforms['uDiffuseColor']) {
        shipMat.uniforms['uDiffuseColor'].value.setHex(bodyColor);
        console.log('launch.js: Applied ship color (ShaderMaterial) 0x' + bodyColor.toString(16));
      }
      // MeshBasicMaterial / MeshPhongMaterial — .color property
      else if (shipMat.color && typeof shipMat.color.setHex === 'function') {
        shipMat.color.setHex(bodyColor);
        console.log('launch.js: Applied ship color (BasicMaterial) 0x' + bodyColor.toString(16));
      }

      if (bkcore.garage && bkcore.garage.MaterialPresets) {
        bkcore.garage.MaterialPresets.applyToMaterial(shipMat, materialPreset);
        console.log('launch.js: Applied material preset ' + materialPreset);
      }

      // Apply booster light color
      // Try to find PointLights and booster meshes via the ship mesh children
      var shipControls = hexGL.components.shipControls;
      var shipMesh = shipControls && shipControls.mesh;
      if (shipMesh) {
        applyEngineColorToNode(shipMesh, engineColor, shipMesh);
      }
      
      // Apply trail color
      if (hexGL.components.shipEffects) {
        hexGL.components.shipEffects.updateParticleTrail(trailColor, trailSize);
      }
    } catch(e) {
      console.warn('launch.js: Error applying garage customization', e);
    }
  }

  init = function(controlType, quality, hud, godmode) {
    var hexGL, progressbar;
    hexGL = new bkcore.hexgl.HexGL({
      document: document,
      width: window.innerWidth,
      height: window.innerHeight,
      container: $('main'),
      overlay: $('overlay'),
      gameover: $('step-5'),
      quality: quality,
      difficulty: 0,
      hud: hud === 1,
      controlType: controlType,
      godmode: godmode,
      track: 'Cityscape'
    });
    window.hexGL = hexGL;
    progressbar = $('progressbar');
    return hexGL.load({
      onLoad: function() {
        console.log('LOADED.');
        hexGL.init();

        // ── Apply garage customization to the in-game ship ──
        applyGarageColorsToGame(hexGL);

        $('step-3').style.display = 'none';
        $('step-4').style.display = 'block';
        return hexGL.start();
      },
      onError: function(s) {
        return console.error("Error loading " + s + ".");
      },
      onProgress: function(p, t, n) {
        console.log("LOADED " + t + " : " + n + " ( " + p.loaded + " / " + p.total + " ).");
        return progressbar.style.width = "" + (p.loaded / p.total * 100) + "%";
      }
    });
  };

  u = bkcore.Utils.getURLParameter;

  defaultControls = bkcore.Utils.isTouchDevice() ? 1 : 0;

  s = [['controlType', ['KEYBOARD', 'TOUCH', 'LEAP MOTION CONTROLLER', 'GAMEPAD'], defaultControls, defaultControls, 'Controls: '], ['quality', ['LOW', 'MID', 'HIGH', 'VERY HIGH'], 3, 3, 'Quality: '], ['hud', ['OFF', 'ON'], 1, 1, 'HUD: '], ['godmode', ['OFF', 'ON'], 0, 1, 'Godmode: ']];

  _fn = function(a) {
    var e, f, _ref;
    a[3] = (_ref = u(a[0])) != null ? _ref : a[2];
    e = $("s-" + a[0]);
    (f = function() {
      return e.innerHTML = a[4] + a[1][a[3]];
    })();
    return e.onclick = function() {
      return f(a[3] = (a[3] + 1) % a[1].length);
    };
  };
  for (_i = 0, _len = s.length; _i < _len; _i++) {
    a = s[_i];
    _fn(a);
  }

  $('step-2').onclick = function() {
    $('step-2').style.display = 'none';
    $('step-3').style.display = 'block';
    return init(s[0][3], s[1][3], s[2][3], s[3][3]);
  };

  $('step-5').onclick = function() {
    return window.location.reload();
  };

  $('s-credits').onclick = function() {
    $('step-1').style.display = 'none';
    return $('credits').style.display = 'block';
  };

  $('credits').onclick = function() {
    $('step-1').style.display = 'block';
    return $('credits').style.display = 'none';
  };

  // ═══════════════════════════════════════════════════════════
  //  GARAGE — Navigation & Panel Logic
  // ═══════════════════════════════════════════════════════════

  var garagePanelOpen = false;

  // ── Trail color state ──
  var currentTrailColor = '#ffffff';
  var currentTrailSize = 2;
  var currentMaterialPreset = 'metallic';

  function loadGarageDetailState() {
    try {
      var prefs = bkcore.garage.GaragePreferences.load();
      if (prefs && prefs.ship) {
        if (prefs.ship.colors && prefs.ship.colors.trail) {
          currentTrailColor = prefs.ship.colors.trail;
        } else if (prefs.ship.trail && prefs.ship.trail.color) {
          currentTrailColor = prefs.ship.trail.color;
        }

        if (prefs.ship.particles && typeof prefs.ship.particles.size === 'number') {
          currentTrailSize = prefs.ship.particles.size;
        } else if (prefs.ship.trail && typeof prefs.ship.trail.size === 'number') {
          currentTrailSize = prefs.ship.trail.size;
        }

        if (prefs.ship.material && prefs.ship.material.preset) {
          currentMaterialPreset = prefs.ship.material.preset;
        }
      }
    } catch(e) {}
  }

  function setTrailColor(hexString) {
    currentTrailColor = hexString;
  }

  function setTrailSize(size) {
    currentTrailSize = size;
  }

  function setMaterialPreset(preset) {
    currentMaterialPreset = preset;
  }

  function returnToMenu() {
    // Close panel if open
    closePanelIfOpen();
    $('garage').style.display = 'none';
    $('step-1').style.display = 'block';
    GarageRenderer.destroy();
  }

  function preventGarageClickBubble(event) {
    if (!event) return;
    event.stopPropagation();
    if (event.stopImmediatePropagation) {
      event.stopImmediatePropagation();
    }
  }

  // ── Toast Notification ──
  function showToast(message) {
    var toast = $('garage-toast');
    if (!toast) return;
    toast.textContent = message;
    toast.classList.add('show');
    setTimeout(function() {
      toast.classList.remove('show');
    }, 2200);
  }

  // ── Save ──
  function saveGarageState() {
    var success = GarageRenderer.saveCustomization();
    var saveBtn = $('garage-save');
    if (success) {
      if (saveBtn) {
        saveBtn.classList.add('saved');
        setTimeout(function() {
          saveBtn.classList.remove('saved');
        }, 1000);
      }
      showToast('Guardado');
    } else {
      showToast('No se pudo guardar');
    }
  }

  // ── Panel toggle ──
  function togglePanel() {
    garagePanelOpen = !garagePanelOpen;
    var panel = $('garage-panel');
    var viewport = $('garage-viewport');
    var toggleBtn = $('garage-toggle-panel');

    if (garagePanelOpen) {
      panel.classList.add('open');
      viewport.classList.add('panel-open');
      toggleBtn.classList.add('panel-active');
      // Sync swatches with current customization
      syncSwatchesWithState();
    } else {
      panel.classList.remove('open');
      viewport.classList.remove('panel-open');
      toggleBtn.classList.remove('panel-active');
    }

    // Trigger resize so the 3D viewport adjusts its aspect ratio
    setTimeout(function() {
      GarageRenderer.onWindowResize();
    }, 400);
  }

  function closePanelIfOpen() {
    if (garagePanelOpen) {
      garagePanelOpen = false;
      var panel = $('garage-panel');
      var viewport = $('garage-viewport');
      var toggleBtn = $('garage-toggle-panel');
      if (panel) panel.classList.remove('open');
      if (viewport) viewport.classList.remove('panel-open');
      if (toggleBtn) toggleBtn.classList.remove('panel-active');
    }
  }

  // ── Sync swatch active state with current customization ──
  function syncSwatchesWithState() {
    var state = GarageRenderer.getCustomization();

    // Ship color swatches
    var shipSwatches = document.querySelectorAll('#ship-color-grid .color-swatch');
    for (var i = 0; i < shipSwatches.length; i++) {
      var colorVal = parseInt(shipSwatches[i].getAttribute('data-color'));
      if (colorVal === state.shipColor) {
        shipSwatches[i].classList.add('active');
      } else {
        shipSwatches[i].classList.remove('active');
      }
    }
    // Update custom picker
    var shipPicker = $('ship-custom-color');
    if (shipPicker) shipPicker.value = garageColorNumberToHexString(state.shipColor);

    // Booster color swatches
    var boosterSwatches = document.querySelectorAll('#booster-color-grid .color-swatch');
    for (var j = 0; j < boosterSwatches.length; j++) {
      var bColorVal = parseInt(boosterSwatches[j].getAttribute('data-color'));
      if (bColorVal === state.boosterColor) {
        boosterSwatches[j].classList.add('active');
      } else {
        boosterSwatches[j].classList.remove('active');
      }
    }
    // Update custom picker
    var boosterPicker = $('booster-custom-color');
    if (boosterPicker) boosterPicker.value = garageColorNumberToHexString(state.boosterColor);

    // Material preset buttons
    currentMaterialPreset = state.materialPreset;
    var materialButtons = document.querySelectorAll('#material-preset-grid .material-preset');
    for (var m = 0; m < materialButtons.length; m++) {
      if (materialButtons[m].getAttribute('data-preset') === currentMaterialPreset) {
        materialButtons[m].classList.add('active');
      } else {
        materialButtons[m].classList.remove('active');
      }
    }

    // Trail color swatches
    currentTrailColor = garageColorNumberToHexString(state.trailColor);
    var currentTrailNum = state.trailColor;
    var trailSwatches = document.querySelectorAll('#trail-color-grid .color-swatch');
    for (var k = 0; k < trailSwatches.length; k++) {
      var tColorVal = parseInt(trailSwatches[k].getAttribute('data-color'));
      if (tColorVal === currentTrailNum) {
        trailSwatches[k].classList.add('active');
      } else {
        trailSwatches[k].classList.remove('active');
      }
    }
    var trailPicker = $('trail-custom-color');
    if (trailPicker) trailPicker.value = currentTrailColor;

    currentTrailSize = state.trailSize;
    var trailSizeInput = $('trail-size');
    if (trailSizeInput) trailSizeInput.value = currentTrailSize;
    var trailSizeValue = $('trail-size-value');
    if (trailSizeValue) trailSizeValue.textContent = currentTrailSize.toFixed(1);
  }

  // ── Open Garage ──
  $('s-garage').onclick = function() {
    $('step-1').style.display = 'none';
    $('garage').style.display = 'block';
    loadGarageDetailState();
    GarageRenderer.init($('garage-viewport'));
    syncSwatchesWithState();
  };

  // ── Setup event listeners ──
  function setupGarageListeners() {
    // Prevent clicks from bubbling through the garage
    $('garage').addEventListener('click', preventGarageClickBubble);
    var viewportEl = $('garage-viewport');
    if (viewportEl) {
      viewportEl.addEventListener('click', preventGarageClickBubble);
    }

    // ── Panel toggle ──
    $('garage-toggle-panel').onclick = function(event) {
      preventGarageClickBubble(event);
      togglePanel();
      return false;
    };

    // ── Ship color swatches ──
    var shipGrid = $('ship-color-grid');
    if (shipGrid) {
      shipGrid.addEventListener('click', function(event) {
        var swatch = event.target.closest('.color-swatch');
        if (!swatch) return;
        preventGarageClickBubble(event);

        var colorHex = parseInt(swatch.getAttribute('data-color'));
        GarageRenderer.setShipColor(colorHex);

        // Update active state
        var siblings = shipGrid.querySelectorAll('.color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
        swatch.classList.add('active');

        // Update custom picker to match
        var picker = $('ship-custom-color');
        if (picker) picker.value = garageColorNumberToHexString(colorHex);
      });
    }

    // ── Ship custom color picker ──
    var shipPicker = $('ship-custom-color');
    if (shipPicker) {
      shipPicker.addEventListener('input', function() {
        var hexVal = parseInt(this.value.replace('#', ''), 16);
        GarageRenderer.setShipColor(hexVal);

        // Deactivate all preset swatches
        var siblings = shipGrid.querySelectorAll('.color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
      });
    }

    // ── Booster color swatches ──
    var boosterGrid = $('booster-color-grid');
    if (boosterGrid) {
      boosterGrid.addEventListener('click', function(event) {
        var swatch = event.target.closest('.color-swatch');
        if (!swatch) return;
        preventGarageClickBubble(event);

        var colorHex = parseInt(swatch.getAttribute('data-color'));
        GarageRenderer.setBoosterColor(colorHex);

        // Update active state
        var siblings = boosterGrid.querySelectorAll('.color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
        swatch.classList.add('active');

        // Update custom picker to match
        var picker = $('booster-custom-color');
        if (picker) picker.value = garageColorNumberToHexString(colorHex);
      });
    }

    // ── Booster custom color picker ──
    var boosterPicker = $('booster-custom-color');
    if (boosterPicker) {
      boosterPicker.addEventListener('input', function() {
        var hexVal = parseInt(this.value.replace('#', ''), 16);
        GarageRenderer.setBoosterColor(hexVal);

        // Deactivate all preset swatches
        var siblings = boosterGrid.querySelectorAll('.color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
      });
    }

    // ── Material preset buttons ──
    var materialGrid = $('material-preset-grid');
    if (materialGrid) {
      materialGrid.addEventListener('click', function(event) {
        var button = event.target.closest('.material-preset');
        if (!button) return;
        preventGarageClickBubble(event);

        var preset = button.getAttribute('data-preset');
        setMaterialPreset(preset);
        GarageRenderer.setMaterialPreset(preset);

        var siblings = materialGrid.querySelectorAll('.material-preset');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
        button.classList.add('active');
      });
    }

    // ── Trail color swatches ──
    var trailGrid = $('trail-color-grid');
    if (trailGrid) {
      trailGrid.addEventListener('click', function(event) {
        var swatch = event.target.closest('.color-swatch');
        if (!swatch) return;
        preventGarageClickBubble(event);

        var colorHex = parseInt(swatch.getAttribute('data-color'));
        var hexString = garageColorNumberToHexString(colorHex);
        setTrailColor(hexString);
        GarageRenderer.setTrailColor(colorHex);

        var siblings = trailGrid.querySelectorAll('.color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
        swatch.classList.add('active');

        var picker = $('trail-custom-color');
        if (picker) picker.value = hexString;
      });
    }

    // ── Trail custom color picker ──
    var trailPickerEl = $('trail-custom-color');
    if (trailPickerEl) {
      trailPickerEl.addEventListener('input', function() {
        setTrailColor(this.value);
        GarageRenderer.setTrailColor(parseInt(this.value.replace('#', ''), 16));
        var siblings = document.querySelectorAll('#trail-color-grid .color-swatch');
        for (var i = 0; i < siblings.length; i++) {
          siblings[i].classList.remove('active');
        }
      });
    }

    // ── Trail size slider ──
    var trailSizeEl = $('trail-size');
    if (trailSizeEl) {
      trailSizeEl.addEventListener('input', function() {
        var size = parseFloat(this.value);
        setTrailSize(size);
        GarageRenderer.setTrailSize(size);
        var valueEl = $('trail-size-value');
        if (valueEl) valueEl.textContent = size.toFixed(1);
      });
    }

    // ── Reset button ──
    var resetBtn = $('garage-reset-colors');
    if (resetBtn) {
      resetBtn.onclick = function(event) {
        preventGarageClickBubble(event);
        var defaults = bkcore.garage.GaragePreferences.getDefaults();
        GarageRenderer.setShipColor(garageHexStringToNumber(defaults.ship.colors.body));
        GarageRenderer.setBoosterColor(garageHexStringToNumber(defaults.ship.colors.engine));
        setTrailColor(defaults.ship.colors.trail);
        setTrailSize(defaults.ship.particles.size);
        setMaterialPreset(defaults.ship.material.preset);
        GarageRenderer.setTrailColor(garageHexStringToNumber(defaults.ship.colors.trail));
        GarageRenderer.setTrailSize(defaults.ship.particles.size);
        GarageRenderer.setMaterialPreset(defaults.ship.material.preset);
        syncSwatchesWithState();
        showToast('↺ Colores restablecidos');
        return false;
      };
    }
  }

  setupGarageListeners();

  // ── Save button ──
  $('garage-save').onclick = function(event) {
    preventGarageClickBubble(event);
    saveGarageState();
    return false;
  };

  // ── Back button ──
  $('garage-back').onclick = function(event) {
    preventGarageClickBubble(event);
    returnToMenu();
    return false;
  };

  hasWebGL = function() {
    var canvas, gl;
    gl = null;
    canvas = document.createElement('canvas');
    try {
      gl = canvas.getContext("webgl");
    } catch (_error) {}
    if (gl == null) {
      try {
        gl = canvas.getContext("experimental-webgl");
      } catch (_error) {}
    }
    return gl != null;
  };

  if (!hasWebGL()) {
    getWebGL = $('start');
    getWebGL.innerHTML = 'WebGL is not supported!';
    getWebGL.onclick = function() {
      return window.location.href = 'http://get.webgl.org/';
    };
  } else {
    $('start').onclick = function() {
      $('step-1').style.display = 'none';
      $('step-2').style.display = 'block';
      return $('step-2').style.backgroundImage = "url(css/help-" + s[0][3] + ".png)";
    };
  }

}).call(this);
